### ISSUE TITLE
Add Route transition

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [SidKwok/github-explorer#3]
@SidKwok , I would like to add the _**route transitions**_, just to be sure. Do you want to add transition animation to the router links? If so, which animations would you like to add? Can you point me to them? I will make sure to add them.

**Comment by SidKwok** [comment]
Sorry for my overdue reply.
I didn't do animations because I just started to learn Vue that time, and I am not an expert in animations lol. If you got any good idea on animations, feel free to make it happen in this project. As for me, I think some route transitions are required:
1. main page -> repositories page
2. repositories page -> detail page, smoother I think

**Comment by SidKwok** [comment]
And thanks again for your help and enthusiasm!

**Comment by Manuel-Suarez-Abascal** [comment]
> 1. main page -> repositories page
> 2. repositories page -> detail page, smoother I think

@SidKwok Thanks for your reply, my pleasure to help! It allows me to practice, learn and give back!

1. Do you mean when I click on these buttons/links?

![view-repo-link](https://user-images.githubusercontent.com/32891808/59895527-e790d080-93b2-11e9-89cc-5623c01c3717.jpg)
![view-repo-link2](https://user-images.githubusercontent.com/32891808/59895531-eb245780-93b2-11e9-8f82-ad52a9c5e861.jpg)

2. Do you mean when I click on any repo and brings you to the repo details page? If so, you want to animate the repo-content or repo-tab-content section(which already has an animation) or  both?

I am planning to use some animation from [animate.css](https://daneden.github.io/animate.css/)

**Comment by SidKwok** [comment]
1. Yup
2. Yup. But I think it can be smoother.

Feel free to use any library for transitions.

**Comment by Manuel-Suarez-Abascal** [comment]
@SidKwok I just finished working on it, waiting for PR review! :)

**Comment by SidKwok** [comment]
Merged.
