### ISSUE TITLE
RepoList component doesn't re-render when refreshing browser window

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [SidKwok/github-explorer#5]
@SidKwok  while working on the animations ticket, I discovered a bug. 

When you click the in the buttons "View Repositories", it takes you to the repository list. However, if you refresh the browser while in repository list window the repo list disappear & doesn't re-render.

Please, try to recreate it on your side to confirm this bug.

I could work on this bug, if you want...

**Comment by SidKwok** [comment]
You can submit a pr for this issue.

**Comment by Manuel-Suarez-Abascal** [comment]
> You can submit a pr for this issue.

Awesome, I will start working on it as soon as I have some time. I will remove the tag "Needs Review" and add "Confirmed". Cheers!

**Comment by Manuel-Suarez-Abascal** [comment]
@SidKwok I have have been playing a lot of with that code base to fix this issue. It seems that this is Vuex expected behavior. There are some way to fix it though and I found this:

https://stackoverflow.com/questions/43027499/vuex-state-on-page-refresh

https://github.com/robinvdvleuten/vuex-persistedstate

Let me know, if you find something on your side.
